### ISSUE TITLE
Possibility to add styles to mbtiles cache

### ISSUE THREAD

**Issue by a14stoner** [BergWerkGIS/vtpk2mbtiles#4]
Hello i followed your converting script. 

Now I have the same result as you. The raw vektor data. Is it somehow possible to apply the provided styles that the map looks like here: 

![image](https://user-images.githubusercontent.com/59861665/223673737-d9f57777-c694-4d9b-90a2-78dc5b8b502f.png)

Thanks in advance. 
Best regards
Andy

**Comment by wilhelmberg** [comment]
@a14stoner the concept of Mapbox Vector Tiles is that data and style rules for rendering are separate.

You find the style in the folder where you extracted `bmapv_vtpk_3857.vtpk` to:
```
p12/resources/styles/root.json
```

You need a renderer like MapLibre GL JS, MapLibre GL Native or even QGIS to combine the MVTs and the style into a map like in the screenshot.

But be aware, the style (`root.json`) is not properly formatted and does not work with any OSS out of the box.

You also need to incorporate the fonts and sprites that come with the VTPK.

I think you need to dig a little deeper into the concept of MVTs and styles and the how the rendering of those works before you are able to produce a map.

Good starting points would most likely be the MapLibre or Mapbox docs.

**Comment by a14stoner** [comment]
I managed to render the bap with tileserver-gl: 

![image](https://user-images.githubusercontent.com/59861665/224270295-9443406f-cf1b-4350-ac08-baa1ac8c96df.png)

but what is interesting: No hillshading data is here: 

![image](https://user-images.githubusercontent.com/59861665/224270457-260d2dc3-1eea-4365-9296-83c4b61f32dd.png)

When opening the rar vtpk file (downloaded here: https://cdn.basemap.at/offline/bmapv_vtpk_3857.vtpk) hillshading is also not present:

![image](https://user-images.githubusercontent.com/59861665/224269917-26a7182e-7e43-4b0e-905e-3a4cba490f75.png)
 
When checking the data.gv.at website (https://www.data.gv.at/2019/06/25/basemap-at-vektor-tile-cache/) hillshading is there. 


any idea? :D 

P.S.: Should i share my configuration here? 

- Config for tileserver-gl
- styles config for basemap

**Comment by a14stoner** [comment]
Nevermind: https://www.data.gv.at/katalog/dataset/basemap-at-hohenlinien-vektor-offline-osterreich#resources

There is an extra vektor file for this.
