### ISSUE TITLE
error in basemap vector files

### ISSUE THREAD

**Issue by a14stoner** [BergWerkGIS/vtpk2mbtiles#5]
Hello, i did not know how where to write you about an issue i found with the basemap vector project (https://basemap.at/standard-5)

I reported an issue at the fileserver-gl project: https://github.com/maptiler/tileserver-gl/issues/1034#issuecomment-1867408635
The problem here is that vector data is not avaliable at some zoom levels: 

i tried it with the offline vtpk file and the online source. 
The error also appeares here: https://trafficon.github.io/basemap-at-maplibre/

![image](https://github.com/BergWerkGIS/vtpk2mbtiles/assets/59861665/9bfa90e7-a263-4317-9e62-3bfae5ee5a32)

I know there is some mail to send this issue to: viennagis@post.wien.gv.at but i dont expect a fast answer there.anyways i also sent a mail with this problem to this mail.  since i know you made this i thought ill report this in some of your project. 

best regards
andy

**Comment by wilhelmberg** [comment]
@a14stoner thanks for reporting, but this is a known issue.
The dataset is missing some tiles here and there.
Be patient, this will improve next year.
